server:
  port: 8805

spring:
  application:
    name: @pom.name@
  sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0  #default:0.1, it is portion of sample. 1.0 means grab all sample.
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
