server:
  port: 8761

spring:
  application:
    name: @pom.name@

eureka:
  instance:
    hostname: localhost
  client:
#  是否要注册到其他Eureka实例
    register-with-eureka: true
#  是否要从其他Eureka实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

