spring:
  application:
    name: @pom.name@
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config: microservice-consumer-engine, microservice-provider-searcher
  cluster-name-expression: new String("default")
  combine-host-port: true


