spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: @pom.name@
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 10000

eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

