spring:
  application:
    name: @pom.name@
#    开启通过服务中心自动根据serviceId创建路由

server:
  port: 10000

eureka:
  client:
    service-url:
      defualtZone: http://192.168.92.2:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug

